--DATA PREPARATION AND UNDERSTANDING

--1. What is the total number of rows in each of the 3 tables in the database?

SELECT Total_Rows = COUNT(*) FROM Customer
SELECT Total_Rows = COUNT(*) FROM prod_cat_info
SELECT Total_Rows = COUNT(*) FROM Transactions



--2. What is the total number of transactions that have a return?

SELECT 
Total_transactions = COUNT(transaction_id) 
FROM Transactions
WHERE Qty < 0



/*** 3. As you would have noticed, the dates provided across the datasets are not in a correct format. 
		As first steps, pls convert the date variables into valid date formats before proceeding ahead. ****/

-- SELECT CONVERT(Date, DOB, 105) AS DOB FROM Customer
-- SELECT CONVERT(Date, tran_date, 105) AS tran_date FROM Transactions

--Permanent changes in database
UPDATE Transactions
SET tran_date = CONVERT(Date, tran_date, 105)

UPDATE Customer
SET DOB = CONVERT(Date, DOB, 105)


/*** 4.	What is the time range of the transaction data available for analysis? Show the output in number of days, 
		months and years simultaneously	in different columns. ***/

SELECT 
[No_Of_Days] = DATEDIFF(DAY, MIN(tran_date), MAX(tran_date)),
[No_Of_Months] = DATEDIFF(MONTH, MIN(tran_date), MAX(tran_date)),
[No_Of_Years] = DATEDIFF(YEAR, MIN(tran_date), MAX(tran_date))
FROM Transactions

SELECT * FROM Transactions

--5.	Which product category does the sub-category “DIY” belong to?

SELECT prod_cat FROM prod_cat_info WHERE prod_subcat = 'DIY'



--DATA ANALYSIS 

--1. Which Channel is most frequently used for transactions?

SELECT TOP 1
Store_type
--,CountIDs = COUNT(transaction_id)
FROM Transactions
GROUP BY Store_type
ORDER BY COUNT(transaction_id) DESC


--2. What is the count of Male and Female customers in the database?

SELECT 
Gender,
[Count] = COUNT(customer_Id)

FROM Customer
WHERE Gender IN ('F', 'M')

GROUP BY Gender



--3. From which city do we have the maximum number of customers and how many?

SELECT 
TOP 1 city_code, 
No_Of_Customers = COUNT(customer_id)
FROM Customer
GROUP BY city_code
ORDER BY No_Of_Customers DESC



--4. How many sub-categories are there under the Books category?

SELECT 
Count_SubCat = COUNT(prod_subcat)
FROM prod_cat_info
WHERE prod_cat = 'Books'
GROUP BY prod_cat



--5. What is the maximum quantity of products ever ordered?

SELECT TOP 1 
Qty AS Max_Qty
-- ABS(Qty)
FROM Transactions
ORDER BY Qty DESC



--6. What is the net total revenue generated in categories Electronics and Books?

SELECT * FROM Transactions

/**UPDATE Transactions
SET total_amt = CAST(total_amt AS float)**/

SELECT 
Net_Revenue = SUM(CAST(total_amt AS float))

FROM Transactions T1
INNER JOIN prod_cat_info T2
	ON T1.prod_cat_code = T2.prod_cat_code 
	AND T1.prod_subcat_code = T2.prod_sub_cat_code
	WHERE prod_cat IN ('Electronics', 'Books')



--7. How many customers have >10 transactions with us, excluding returns?

SELECT 
Cust_Count = COUNT(cust_Id)

FROM Transactions 
 
WHERE cust_id IN 
	(
		SELECT cust_id
		FROM Transactions
		WHERE Qty > 0
		GROUP BY cust_id
		HAVING COUNT(transaction_id) > 10
	)


--8. What is the combined revenue earned from the “Electronics” & “Clothing” categories, from “Flagship stores”?

SELECT
Combined_Revenue = SUM(CAST(total_amt AS float))

FROM Transactions T1
	INNER JOIN prod_cat_info T2
	ON T1.prod_cat_code = T2.prod_cat_code
	AND T1.prod_subcat_code = T2.prod_sub_cat_code
WHERE prod_cat IN ('Electronics', 'Clothing')
	AND Store_type = 'Flagship store'



--9. What is the total revenue generated from “Male” customers in “Electronics” category? Output should display total revenue by prod sub-cat.

SELECT 
prod_subcat,
Total_Rev_Male = SUM(CAST(total_amt AS float))

FROM Transactions T1
	INNER JOIN prod_cat_info T2
	ON T1.prod_cat_code = T2.prod_cat_code
	AND T1.prod_subcat_code = T2.prod_sub_cat_code

	INNER JOIN Customer T3
	ON T1.cust_id = T3.customer_Id

WHERE Gender = 'M'
	AND prod_cat = 'Electronics'

GROUP BY prod_subcat



--10. What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales?

DECLARE @TotalAmt Float = (SELECT SUM(CAST(total_amt AS float)) FROM Transactions)

SELECT TOP 5
prod_subcat,
Return_Percent = (SUM(CAST(CASE WHEN Qty < 0 THEN ABS(total_amt) Else NULL End AS float))/ @TotalAmt) * 100,
Sales_Percent = (SUM(CAST(CASE WHEN Qty > 0 THEN total_amt Else NULL End AS float))/ @TotalAmt) * 100

FROM Transactions T1
	INNER JOIN prod_cat_info T2
	ON T1.prod_cat_code = T2.prod_cat_code
	AND T1.prod_subcat_code = T2.prod_sub_cat_code

GROUP BY prod_subcat

ORDER BY SUM(CAST(total_amt AS float)) DESC



/*** 11. For all customers aged between 25 to 35 years, find what is the net total revenue generated by these consumers in last 30 days of transactions
	from max transaction date available in the data? ***/

DECLARE @MaxTran_Date DATE = (SELECT MAX(CONVERT(DATE,tran_date,105)) FROM Transactions)

SELECT 
cust_id,
Net_Total_Revenue = SUM(CAST(total_amt AS float))

FROM Transactions
WHERE cust_id IN
	(
	SELECT customer_Id
	FROM Customer
	WHERE DATEDIFF(YEAR, CONVERT(DATE, DOB, 105), GETDATE()) BETWEEN 25 AND 35
		AND CONVERT(DATE,tran_date,105) >= DATEADD(DAY, -30, @MaxTran_Date)
	)
GROUP BY cust_id



--12. Which product category has seen the max value of returns in the last 3 months of transactions?

DECLARE @MaxDate DATE = (SELECT MAX(CONVERT(DATE, tran_date, 105)) FROM Transactions)

SELECT TOP 1 
prod_cat, 
TotalAmt = SUM(CAST(total_amt AS float))

FROM Transactions T1
	INNER JOIN prod_cat_info T2 
	ON T1.prod_cat_code = T2.prod_cat_code AND 
		T1.prod_subcat_code = T2.prod_sub_cat_code

WHERE Qty < 0 
	 AND CONVERT(DATE, tran_date, 105) BETWEEN DATEADD(MONTH,-3, @MaxDate) 
	 AND @MaxDate

GROUP BY prod_cat

ORDER BY TotalAmt DESC



--13. Which store-type sells the maximum products; by value of sales amount and	by quantity sold?

SELECT TOP 1
Store_type, 
Total_Sales = SUM(CAST(CASE WHEN Qty > 0 THEN total_amt Else NULL End AS float)), 
Total_Qty = SUM(CAST(CASE WHEN Qty > 0 THEN Qty Else NULL End AS int))

FROM Transactions

GROUP BY Store_type
ORDER BY Total_Qty DESC, Total_Sales DESC



--14. What are the categories for which average revenue is above the overall average?

SELECT 
prod_cat, 
Avg_Revenue = AVG(CAST(total_amt AS float))

FROM Transactions T
	INNER JOIN prod_cat_info P 
	ON T.prod_cat_code = P.prod_cat_code AND
		T.prod_subcat_code = P.prod_sub_cat_code

GROUP BY prod_cat
HAVING AVG(CAST(total_amt AS float)) > (SELECT AVG(CAST(total_amt AS float)) FROM Transactions) 



--15. Find the average and total revenue by each subcategory for the categories which are among top 5 categories in terms of quantity sold.

SELECT
prod_cat, 
prod_subcat, 
Avg_Rev = AVG(CAST(total_amt AS float)),
Total_Rev = SUM(CAST(total_amt AS float))
FROM Transactions T

	INNER JOIN prod_cat_info P 
	ON T.prod_cat_code = P.prod_cat_code AND
		T.prod_subcat_code = P.prod_sub_cat_code

WHERE prod_cat IN
	(
	SELECT TOP 5 
	prod_cat
	FROM Transactions T
		INNER JOIN prod_cat_info P
		ON T.prod_cat_code = P.prod_cat_code AND
			T.prod_subcat_code = P.prod_sub_cat_code
	GROUP BY prod_cat
	ORDER BY SUM(CAST(QTY AS int)) DESC
	)

GROUP BY prod_cat, prod_subcat
